### ISSUE TITLE
Not on pip

### ISSUE THREAD

**Issue by slundberg** [gnestor/jupyterlab_react#3]
This isn't on pip like the readme suggests. Is the project still active? Thanks!

**Comment by gnestor** [comment]
This is very experimental and not actively maintained, although I'd like to develop it more. I'd love some help! 👍👍

**Comment by slundberg** [comment]
I am not sure how much time I want to invest getting a current notebook interface working in Jupyter lab, but if I do jump into it I'll start here :)
